version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e2y0d3s7
  build:
    commands:
      - docker build -t hi-alan .
      - docker tag hi-alan:latest public.ecr.aws/e2y0d3s7/hi-alan:latest
  post_build:
    commands:
      - docker push public.ecr.aws/e2y0d3s7/hi-alan:latest
      - printf '[{"name":"TD-hialan","imageUri":"%s"}]' public.ecr.aws/e2y0d3s7/hi-alan:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
